#!/bin/bash
bsub -q l -o ./log/udsMC-script-0.log ./scripts/udsMC-script-0.sh
bsub -q l -o ./log/udsMC-script-1.log ./scripts/udsMC-script-1.sh
bsub -q l -o ./log/udsMC-script-2.log ./scripts/udsMC-script-2.sh
bsub -q l -o ./log/udsMC-script-3.log ./scripts/udsMC-script-3.sh
bsub -q l -o ./log/udsMC-script-4.log ./scripts/udsMC-script-4.sh
bsub -q l -o ./log/udsMC-script-5.log ./scripts/udsMC-script-5.sh
bsub -q l -o ./log/udsMC-script-6.log ./scripts/udsMC-script-6.sh
bsub -q l -o ./log/udsMC-script-7.log ./scripts/udsMC-script-7.sh
bsub -q l -o ./log/udsMC-script-8.log ./scripts/udsMC-script-8.sh
bsub -q l -o ./log/udsMC-script-9.log ./scripts/udsMC-script-9.sh
bsub -q l -o ./log/udsMC-script-10.log ./scripts/udsMC-script-10.sh
bsub -q l -o ./log/udsMC-script-11.log ./scripts/udsMC-script-11.sh
bsub -q l -o ./log/udsMC-script-12.log ./scripts/udsMC-script-12.sh
bsub -q l -o ./log/udsMC-script-13.log ./scripts/udsMC-script-13.sh
bsub -q l -o ./log/udsMC-script-14.log ./scripts/udsMC-script-14.sh
bsub -q l -o ./log/udsMC-script-15.log ./scripts/udsMC-script-15.sh
bsub -q l -o ./log/udsMC-script-16.log ./scripts/udsMC-script-16.sh
bsub -q l -o ./log/udsMC-script-17.log ./scripts/udsMC-script-17.sh
bsub -q l -o ./log/udsMC-script-18.log ./scripts/udsMC-script-18.sh
bsub -q l -o ./log/udsMC-script-19.log ./scripts/udsMC-script-19.sh
bsub -q l -o ./log/udsMC-script-20.log ./scripts/udsMC-script-20.sh
bsub -q l -o ./log/udsMC-script-21.log ./scripts/udsMC-script-21.sh
bsub -q l -o ./log/udsMC-script-22.log ./scripts/udsMC-script-22.sh
bsub -q l -o ./log/udsMC-script-23.log ./scripts/udsMC-script-23.sh
bsub -q l -o ./log/udsMC-script-24.log ./scripts/udsMC-script-24.sh
bsub -q l -o ./log/udsMC-script-25.log ./scripts/udsMC-script-25.sh
bsub -q l -o ./log/udsMC-script-26.log ./scripts/udsMC-script-26.sh
bsub -q l -o ./log/udsMC-script-27.log ./scripts/udsMC-script-27.sh
bsub -q l -o ./log/udsMC-script-28.log ./scripts/udsMC-script-28.sh
bsub -q l -o ./log/udsMC-script-29.log ./scripts/udsMC-script-29.sh
bsub -q l -o ./log/udsMC-script-30.log ./scripts/udsMC-script-30.sh
bsub -q l -o ./log/udsMC-script-31.log ./scripts/udsMC-script-31.sh
bsub -q l -o ./log/udsMC-script-32.log ./scripts/udsMC-script-32.sh
bsub -q l -o ./log/udsMC-script-33.log ./scripts/udsMC-script-33.sh
bsub -q l -o ./log/udsMC-script-34.log ./scripts/udsMC-script-34.sh
bsub -q l -o ./log/udsMC-script-35.log ./scripts/udsMC-script-35.sh
bsub -q l -o ./log/udsMC-script-36.log ./scripts/udsMC-script-36.sh
bsub -q l -o ./log/udsMC-script-37.log ./scripts/udsMC-script-37.sh
bsub -q l -o ./log/udsMC-script-38.log ./scripts/udsMC-script-38.sh
bsub -q l -o ./log/udsMC-script-39.log ./scripts/udsMC-script-39.sh
bsub -q l -o ./log/udsMC-script-40.log ./scripts/udsMC-script-40.sh
bsub -q l -o ./log/udsMC-script-41.log ./scripts/udsMC-script-41.sh
bsub -q l -o ./log/udsMC-script-42.log ./scripts/udsMC-script-42.sh
bsub -q l -o ./log/udsMC-script-43.log ./scripts/udsMC-script-43.sh
bsub -q l -o ./log/udsMC-script-44.log ./scripts/udsMC-script-44.sh
bsub -q l -o ./log/udsMC-script-45.log ./scripts/udsMC-script-45.sh
bsub -q l -o ./log/udsMC-script-46.log ./scripts/udsMC-script-46.sh
bsub -q l -o ./log/udsMC-script-47.log ./scripts/udsMC-script-47.sh
bsub -q l -o ./log/udsMC-script-48.log ./scripts/udsMC-script-48.sh
bsub -q l -o ./log/udsMC-script-49.log ./scripts/udsMC-script-49.sh
bsub -q l -o ./log/udsMC-script-50.log ./scripts/udsMC-script-50.sh
bsub -q l -o ./log/udsMC-script-51.log ./scripts/udsMC-script-51.sh
bsub -q l -o ./log/udsMC-script-52.log ./scripts/udsMC-script-52.sh
bsub -q l -o ./log/udsMC-script-53.log ./scripts/udsMC-script-53.sh
bsub -q l -o ./log/udsMC-script-54.log ./scripts/udsMC-script-54.sh
bsub -q l -o ./log/udsMC-script-55.log ./scripts/udsMC-script-55.sh
bsub -q l -o ./log/udsMC-script-56.log ./scripts/udsMC-script-56.sh
bsub -q l -o ./log/udsMC-script-57.log ./scripts/udsMC-script-57.sh
bsub -q l -o ./log/udsMC-script-58.log ./scripts/udsMC-script-58.sh
bsub -q l -o ./log/udsMC-script-59.log ./scripts/udsMC-script-59.sh
bsub -q l -o ./log/udsMC-script-60.log ./scripts/udsMC-script-60.sh
bsub -q l -o ./log/udsMC-script-61.log ./scripts/udsMC-script-61.sh
bsub -q l -o ./log/udsMC-script-62.log ./scripts/udsMC-script-62.sh
bsub -q l -o ./log/udsMC-script-63.log ./scripts/udsMC-script-63.sh
bsub -q l -o ./log/udsMC-script-64.log ./scripts/udsMC-script-64.sh
bsub -q l -o ./log/udsMC-script-65.log ./scripts/udsMC-script-65.sh
bsub -q l -o ./log/udsMC-script-66.log ./scripts/udsMC-script-66.sh
bsub -q l -o ./log/udsMC-script-67.log ./scripts/udsMC-script-67.sh
bsub -q l -o ./log/udsMC-script-68.log ./scripts/udsMC-script-68.sh
bsub -q l -o ./log/udsMC-script-69.log ./scripts/udsMC-script-69.sh
bsub -q l -o ./log/udsMC-script-70.log ./scripts/udsMC-script-70.sh
bsub -q l -o ./log/udsMC-script-71.log ./scripts/udsMC-script-71.sh
bsub -q l -o ./log/udsMC-script-72.log ./scripts/udsMC-script-72.sh
bsub -q l -o ./log/udsMC-script-73.log ./scripts/udsMC-script-73.sh
bsub -q l -o ./log/udsMC-script-74.log ./scripts/udsMC-script-74.sh
bsub -q l -o ./log/udsMC-script-75.log ./scripts/udsMC-script-75.sh
bsub -q l -o ./log/udsMC-script-76.log ./scripts/udsMC-script-76.sh
bsub -q l -o ./log/udsMC-script-77.log ./scripts/udsMC-script-77.sh
bsub -q l -o ./log/udsMC-script-78.log ./scripts/udsMC-script-78.sh
bsub -q l -o ./log/udsMC-script-79.log ./scripts/udsMC-script-79.sh
bsub -q l -o ./log/udsMC-script-80.log ./scripts/udsMC-script-80.sh
bsub -q l -o ./log/udsMC-script-81.log ./scripts/udsMC-script-81.sh
bsub -q l -o ./log/udsMC-script-82.log ./scripts/udsMC-script-82.sh
bsub -q l -o ./log/udsMC-script-83.log ./scripts/udsMC-script-83.sh
bsub -q l -o ./log/udsMC-script-84.log ./scripts/udsMC-script-84.sh
bsub -q l -o ./log/udsMC-script-85.log ./scripts/udsMC-script-85.sh
bsub -q l -o ./log/udsMC-script-86.log ./scripts/udsMC-script-86.sh
bsub -q l -o ./log/udsMC-script-87.log ./scripts/udsMC-script-87.sh
bsub -q l -o ./log/udsMC-script-88.log ./scripts/udsMC-script-88.sh
bsub -q l -o ./log/udsMC-script-89.log ./scripts/udsMC-script-89.sh
bsub -q l -o ./log/udsMC-script-90.log ./scripts/udsMC-script-90.sh
bsub -q l -o ./log/udsMC-script-91.log ./scripts/udsMC-script-91.sh
bsub -q l -o ./log/udsMC-script-92.log ./scripts/udsMC-script-92.sh
bsub -q l -o ./log/udsMC-script-93.log ./scripts/udsMC-script-93.sh
bsub -q l -o ./log/udsMC-script-94.log ./scripts/udsMC-script-94.sh
bsub -q l -o ./log/udsMC-script-95.log ./scripts/udsMC-script-95.sh
bsub -q l -o ./log/udsMC-script-96.log ./scripts/udsMC-script-96.sh
bsub -q l -o ./log/udsMC-script-97.log ./scripts/udsMC-script-97.sh
bsub -q l -o ./log/udsMC-script-98.log ./scripts/udsMC-script-98.sh
bsub -q l -o ./log/udsMC-script-99.log ./scripts/udsMC-script-99.sh
bsub -q l -o ./log/udsMC-script-100.log ./scripts/udsMC-script-100.sh
bsub -q l -o ./log/udsMC-script-101.log ./scripts/udsMC-script-101.sh
bsub -q l -o ./log/udsMC-script-102.log ./scripts/udsMC-script-102.sh
bsub -q l -o ./log/udsMC-script-103.log ./scripts/udsMC-script-103.sh
bsub -q l -o ./log/udsMC-script-104.log ./scripts/udsMC-script-104.sh
bsub -q l -o ./log/udsMC-script-105.log ./scripts/udsMC-script-105.sh
bsub -q l -o ./log/udsMC-script-106.log ./scripts/udsMC-script-106.sh
bsub -q l -o ./log/udsMC-script-107.log ./scripts/udsMC-script-107.sh
bsub -q l -o ./log/udsMC-script-108.log ./scripts/udsMC-script-108.sh
bsub -q l -o ./log/udsMC-script-109.log ./scripts/udsMC-script-109.sh
bsub -q l -o ./log/udsMC-script-110.log ./scripts/udsMC-script-110.sh
bsub -q l -o ./log/udsMC-script-111.log ./scripts/udsMC-script-111.sh
bsub -q l -o ./log/udsMC-script-112.log ./scripts/udsMC-script-112.sh
bsub -q l -o ./log/udsMC-script-113.log ./scripts/udsMC-script-113.sh
bsub -q l -o ./log/udsMC-script-114.log ./scripts/udsMC-script-114.sh
bsub -q l -o ./log/udsMC-script-115.log ./scripts/udsMC-script-115.sh
bsub -q l -o ./log/udsMC-script-116.log ./scripts/udsMC-script-116.sh
bsub -q l -o ./log/udsMC-script-117.log ./scripts/udsMC-script-117.sh
bsub -q l -o ./log/udsMC-script-118.log ./scripts/udsMC-script-118.sh
bsub -q l -o ./log/udsMC-script-119.log ./scripts/udsMC-script-119.sh
bsub -q l -o ./log/udsMC-script-120.log ./scripts/udsMC-script-120.sh
bsub -q l -o ./log/udsMC-script-121.log ./scripts/udsMC-script-121.sh
bsub -q l -o ./log/udsMC-script-122.log ./scripts/udsMC-script-122.sh
bsub -q l -o ./log/udsMC-script-123.log ./scripts/udsMC-script-123.sh
bsub -q l -o ./log/udsMC-script-124.log ./scripts/udsMC-script-124.sh
bsub -q l -o ./log/udsMC-script-125.log ./scripts/udsMC-script-125.sh
bsub -q l -o ./log/udsMC-script-126.log ./scripts/udsMC-script-126.sh
bsub -q l -o ./log/udsMC-script-127.log ./scripts/udsMC-script-127.sh
bsub -q l -o ./log/udsMC-script-128.log ./scripts/udsMC-script-128.sh
bsub -q l -o ./log/udsMC-script-129.log ./scripts/udsMC-script-129.sh
bsub -q l -o ./log/udsMC-script-130.log ./scripts/udsMC-script-130.sh
bsub -q l -o ./log/udsMC-script-131.log ./scripts/udsMC-script-131.sh
bsub -q l -o ./log/udsMC-script-132.log ./scripts/udsMC-script-132.sh
bsub -q l -o ./log/udsMC-script-133.log ./scripts/udsMC-script-133.sh
bsub -q l -o ./log/udsMC-script-134.log ./scripts/udsMC-script-134.sh
bsub -q l -o ./log/udsMC-script-135.log ./scripts/udsMC-script-135.sh
bsub -q l -o ./log/udsMC-script-136.log ./scripts/udsMC-script-136.sh
